version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: pradeep
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  flask:
    build:
      context: ./app  # Use the app folder as the context for building the Flask app
    container_name: flask
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DATABASE: pradeep
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    restart: always

  web:
    build:
      context: ./web  # Use the web folder as the context for building the web service
    container_name: web
    depends_on:
      - flask
    ports:
      - "8002:80"
    restart: always

volumes:
  mysql_data:  # Volume for persisting MySQL data
