version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    image: pradeepdocker125/3-tier-project/web:latest  # Use the same tag for web
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/local/apache2/htdocs/
    networks:
      - app-network

  app:
    build:
      context: ./app  # Ensure context points to the app folder
      dockerfile: Dockerfile
    image: pradeepdocker125/3-tier-project/app:latest  # Use the same tag for app
    ports:
      - "5000:5000"
    depends_on:
      - web
    networks:
      - app-network

  mysql:
    image: pradeepdocker125/3-tier-project/mysql:latest  # Use the same tag for mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tcs
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
