version: '3.7'

services:
  web:
    build:
      context: .  # Your build context
      dockerfile: web/Dockerfile  # Path to the Dockerfile for web service
    image: pradeepdocker125/3-tier-project/web:latest  # Tag the image with your Docker Hub username
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/local/apache2/htdocs/
    networks:
      - app-network

  app:
    build:
      context: ./app  # Ensure context points to the app folder
      dockerfile: Dockerfile  # Path to Dockerfile for app service
    image: pradeepdocker125/3-tier-project/app:latest  # Tag the image with your Docker Hub username
    ports:
      - "5000:5000"
    depends_on:
      - web
    networks:
      - app-network

  mysql:
    image: pradeepdocker125/3-tier-project/mysql:latest  # Use your Docker Hub username for mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tcs
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
