# Use the official MySQL image from Docker Hub
FROM mysql:latest

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=pradeep
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Expose MySQL port
EXPOSE 3306

# Default command (MySQL server starts automatically)
CMD ["mysqld"]
